version: '2'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - application-network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8083:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - application-network
  dowanload_car_service:
    image: alaeldinmusa/dowanload_car_service:latest
    container_name: car-dowanload-container
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: car
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8082:8082"
    networks:
      - application-network
    depends_on:
      - mysql

  car_search_service:
    image: alaeldinmusa/car_search_service:latest
    container_name: car-search-container
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: car
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8081:8081"
    networks:
      - application-network
    depends_on:
      - mysql

  car-service:
    image: alaeldinmusa/car_service:latest
    container_name: car-container
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: car
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - application-network
    depends_on:
      - mysql
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
      - MYSQL_HOST=mysql
    ports:
      - 9411:9411
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - application-network

networks:
  application-network:
    driver: bridge
